# Generated by Django 4.0.3 on 2022-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='Confirmed',
            new_name='NewConfirmed',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='Critical',
            new_name='NewDeaths',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='Deaths',
            new_name='NewRecovered',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='Recovered',
            new_name='TotalConfirmed',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longitude',
        ),
        migrations.AddField(
            model_name='statistics',
            name='TotalDeaths',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='TotalRecovered',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
